import 'dart:ui' show Locale;

/// Simple Map-based localization service for English, Hindi, and Urdu.
///
/// Keeps translations lean — only the UI strings used across the app.
/// To add a new language, add another locale key and translate all strings.
class LocalizationService {
  const LocalizationService();

  static const Map<String, Map<String, String>> _translations = {
    'en': {
      // General
      'appName': 'Blood Donor Network',
      'appTagline': 'Save Lives, Donate Blood',
      'ok': 'OK',
      'cancel': 'Cancel',
      'close': 'Close',
      'retry': 'Retry',
      'save': 'Save',
      'delete': 'Delete',
      'confirm': 'Confirm',
      'loading': 'Loading...',
      'errorGeneric': 'Error: {error}',
      'failedToLoad': 'Failed to load: {error}',
      'pleaseSignIn': 'Please sign in',
      'retryBtn': 'Retry',
      'viewAll': 'View All',

      // Navigation
      'dashboard': 'Dashboard',
      'requests': 'Requests',
      'donors': 'Donors',
      'hospitals': 'Hospitals',
      'bloodBanks': 'Blood Banks',
      'profile': 'Profile',
      'settings': 'Settings',
      'healthTips': 'Health Tips',

      // Auth
      'welcomeBack': 'Welcome Back',
      'signIn': 'Sign In',
      'signUp': 'Sign Up',
      'signOut': 'Sign Out',
      'email': 'Email',
      'password': 'Password',
      'forgotPassword': 'Forgot Password?',
      'dontHaveAccount': "Don't have an account? ",
      'alreadyHaveAccount': 'Already have an account? ',
      'continueWithGoogle': 'Continue with Google',
      'continueWithApple': 'Continue with Apple',
      'register': 'Register',
      'createAccount': 'Create Account',
      'joinNetwork': 'Join the Network',
      'joinNetworkDesc': 'Create your account to start saving lives',
      'iamA': 'I am a...',
      'fullName': 'Full Name',
      'enterFullName': 'Enter your full name',
      'phoneNumber': 'Phone Number',
      'enterPhoneNumber': 'Enter your phone number',
      'confirmPassword': 'Confirm Password',
      'reenterPassword': 'Re-enter your password',
      'enterEmail': 'Enter your email',
      'enterPassword': 'Enter your password',
      'passwordsDoNotMatch': 'Passwords do not match',
      'accountCreated': 'Account created successfully!',
      'donor': 'Donor',
      'patient': 'Patient',
      'donateBloodDesc': 'Donate blood & save lives',
      'requestBloodDesc': 'Request blood in emergencies',
      'orContinueWith': 'OR CONTINUE WITH',
      'resetPassword': 'Reset Password',
      'forgotPasswordTitle': 'Forgot Password?',
      'enterEmailDesc': "Enter your email address and we'll send you instructions to reset your password.",
      'enterRegisteredEmail': 'Enter your registered email',
      'sendResetLink': 'Send Reset Link',
      'backToSignIn': 'Back to Sign In',
      'emailSent': 'Email Sent!',
      'emailSentDesc': 'Check your email for the password reset link. It may take a few minutes to arrive.',
      'verifyEmail': 'Verify Your Email',
      'pleaseVerifyEmail': 'Please verify your email address to enable full access',
      'verify': 'Verify',
      'failedToSendCode': 'Failed to send code: {error}',
      'enter6DigitCode': 'Enter the 6-digit code sent to',
      'verifyEmailBtn': 'Verify Email',
      'didNotReceiveCode': "Didn't receive the code? ",
      'resend': 'Resend',
      'resendIn': 'Resend in {seconds}s',
      'useDifferentEmail': 'Use a different email',
      'youCanAlsoClick': 'You can also click the verification link sent to your email. The app will detect it automatically.',

      // Onboarding
      'skip': 'Skip',
      'next': 'Next',
      'getStarted': 'Get Started',
      'findDonors': 'Find Blood Donors',
      'findDonorsDesc': 'Connect with eligible blood donors in your area instantly during emergencies.',
      'realTimeLocation': 'Real-Time Location',
      'realTimeLocationDesc': 'GPS-powered donor discovery shows you the nearest available donors on a map.',
      'instantNotifications': 'Instant Notifications',
      'instantNotificationsDesc': 'Receive emergency blood requests and respond quickly to save lives.',

      // Dashboard
      'hello': 'Hello',
      'readyToSaveLives': 'Ready to save lives today?',
      'welcomeToApp': 'Welcome to Blood Donor Network',
      'updateProfileMsg': 'Update your profile to check eligibility',
      'bloodGroup': 'Blood Group',
      'donations': 'Donations',
      'unitsDonated': 'Units Donated',
      'age': 'Age',
      'quickActions': 'Quick Actions',
      'findDonorsBtn': 'Find Donors',
      'history': 'History',
      'activeRequests': 'Active Requests',
      'noActiveRequests': 'No active requests',
      'emergencyRequestsHere': 'Emergency requests will appear here',
      'donationSummary': 'Donation Summary',
      'units': 'Units',
      'donorAvailability': 'Donor Availability',
      'availableToDonate': 'You are available to donate',
      'toggleToReceive': 'Toggle to receive requests',
      'notificationsSection': 'Notifications',
      'eligibleToDonate': 'Eligible to Donate',
      'eligibleNow': 'Eligible to donate now',
      'notEligible': 'Not Eligible',

      // Donor Profile
      'donorProfile': 'Donor Profile',
      'bloodDonor': 'Blood Donor',
      'member': 'Member',
      'edit': 'Edit',
      'bloodInformation': 'Blood Information',
      'contact': 'Contact',
      'weight': 'Weight',
      'gender': 'Gender',
      'weightKg': '{weight} kg',
      'nA': 'N/A',
      'available': 'Available',
      'unavailable': 'Unavailable',
      'updateAvailability': 'Update Availability Status',
      'failedToUpdate': 'Failed to update: {error}',
      'editProfile': 'Edit Profile',
      'personalInfo': 'Personal Information',
      'medicalInfo': 'Medical Information',
      'cityAddress': 'City / Address',
      'enterCity': 'Enter your city',
      'getCurrentLocation': 'Get current location',
      'locationSaved': 'Location coordinates saved',
      'saveChanges': 'Save Changes',
      'profileUpdated': 'Profile updated successfully',
      'locationUpdated': 'Location updated successfully!',
      'failedToGetLocation': 'Failed to get location: {error}',
      'loadingProfile': 'Loading profile...',

      // Patient
      'patientDashboard': 'Patient Dashboard',
      'total': 'Total',
      'active': 'Active',
      'fulfilled': 'Fulfilled',
      'myRequests': 'My Requests',
      'createRequest': 'Create Request',
      'newRequest': 'New Request',
      'noRequestsYet': 'No Requests Yet',
      'noRequestsDesc': 'Create an emergency blood request to find donors near you.',
      'bloodGroupBlood': '{bloodGroup} Blood',
      'acceptedBy': 'Accepted by {name}',
      'cancelBtn': 'Cancel',
      'failedToLoadRequests': 'Failed to load requests: {error}',

      // Blood Requests
      'bloodRequests': 'Blood Requests',
      'noBloodRequests': 'No Blood Requests',
      'noRequestsDonor': 'Emergency blood requests will appear here.',
      'noRequestsPatient': 'Create an emergency request to find donors near you.',
      'bloodGroupNeeded': '{bloodGroup} Blood Needed',
      'unitsRequired': '{units} unit(s) required',
      'acceptRequest': 'Accept Request',
      'requestDetails': 'Request Details',
      'patientLabel': 'Patient',
      'bloodGroupLabel': 'Blood Group',
      'unitsLabel': 'Units',
      'priorityLabel': 'Priority',
      'statusLabel': 'Status',
      'acceptedByLabel': 'Accepted By',
      'notesLabel': 'Notes',
      'markAsCompleted': 'Mark as Completed',
      'cancelRequest': 'Cancel Request',
      'acceptAsDonor': 'Accept Request as Donor',
      'requestNotFound': 'Request not found',
      'failedToLoadRequest': 'Failed to load request',
      'loadingRequest': 'Loading request...',
      'completeDonation': 'Complete Donation',
      'donationDate': 'Donation Date',
      'selectDonationDate': 'Select Donation Date',
      'selectHospital': 'Select Hospital',
      'confirmDonation': 'Confirm Donation',
      'optionalRemarks': 'Optional remarks (e.g., condition notes)',
      'remarksLabel': 'Remarks',

      // Nearby Donors
      'findDonorsTitle': 'Find Donors',
      'refreshLocation': 'Refresh location',
      'all': 'All',
      'withinKm': 'Within {distance} km',
      'sortBy': 'Sort by:',
      'nearest': 'Nearest',
      'mostActive': 'Most Active',
      'highDonations': 'High Donations',
      'gettingLocation': 'Getting your location...',
      'searchingForDonors': 'Searching for donors...',
      'searchFailed': 'Search Failed',
      'searchFailedDesc': 'Could not find donors. Please check your connection and try again.',
      'donorsFound': '{count} donor(s) found',
      'donorSelected': '{name} selected',
      'couldNotCall': 'Could not make phone call',
      'noDonorsBloodGroup': 'No {bloodGroup} donors available within {distance} km',
      'noDonorsDistance': 'No available donors within {distance} km',
      'tryAdjusting': 'Try increasing the distance or changing the blood group filter.',

      // Hospitals
      'hospitalsTitle': 'Hospitals',
      'searchHospitals': 'Search hospitals...',
      'noHospitalsFound': 'No Hospitals Found',
      'noHospitalsMatch': 'No hospitals match your search. Try a different term.',
      'noHospitalsDir': 'Hospital directory will appear here once registered hospitals are available.',
      'verified': 'Verified',
      'call': 'Call',
      'navigate': 'Navigate',
      'couldNotOpenMaps': 'Could not open maps',
      'failedToLoadHospitals': 'Failed to load hospitals',
      'hospitalsWillAppear': 'Hospitals will appear here once registered.',

      // Blood Banks
      'bloodBanksTitle': 'Blood Banks',
      'searchBloodBanks': 'Search blood banks...',
      'noBloodBanksFound': 'No Blood Banks Found',
      'noBloodBanksMatch': 'No blood banks match your search. Try a different term.',
      'bloodBanksWillAppear': 'Blood banks will appear here once registered.',
      'failedToLoadBloodBanks': 'Failed to load blood banks',
      'registerBloodBank': 'Register Blood Bank',
      'bloodBankRegistered': 'Blood bank registered successfully!',
      'registerBloodBankTitle': 'Register Blood Bank',
      'registerBloodBankDesc': 'Add a blood bank to the network so donors and hospitals can find your location.',
      'bloodBankName': 'Blood Bank Name *',
      'address': 'Address',
      'locationRequired': 'Location *',
      'tapToSelectLocation': 'Tap to open map and select location',
      'pleaseSelectLocation': 'Please select a location on the map',

      // Donation History
      'donationHistory': 'Donation History',
      'donorLevel': 'Donor Level',
      'totalDons': 'Total Dons',
      'lastDonation': 'Last Donation',
      'nextEligible': 'Next Eligible',
      'none': 'None',
      'historySection': 'History',
      'atHospital': 'At {name}',
      'aHospital': 'a hospital',
      'achievements': 'Achievements',
      'firstBlood': 'First Blood',
      'superDonor': 'Super Donor',
      'hero': 'Hero',
      'make1Donation': 'Make 1 donation',
      'reach5Donations': 'Reach 5 donations',
      'reach10Donations': 'Reach 10 donations',
      'noDonationsYet': 'No Donations Yet',
      'donationsWillAppear': 'Your donation history will appear here after your first donation.',
      'failedToLoadStats': 'Failed to load stats: {error}',
      'newLevel': 'New',
      'bronze': 'Bronze',
      'silver': 'Silver',
      'gold': 'Gold',

      // Notifications
      'notificationsTitle': 'Notifications',
      'markAllRead': 'Mark All Read ({count})',
      'noNotifications': 'No Notifications',
      'noNotificationsDesc': "You'll receive notifications about emergency requests, updates, and announcements here.",
      'failedToLoadNotifications': 'Failed to load notifications',
      'view': 'View',
      'notificationDetail': 'Notification',
      'deleteNotification': 'Delete Notification',
      'deleteNotificationConfirm': 'Are you sure you want to delete this notification?',
      'share': 'Share',
      'notificationCopied': 'Notification copied to clipboard',
      'emergencyAlert': 'Emergency Alert',
      'reminder': 'Reminder',
      'announcement': 'Announcement',
      'general': 'General',
      'detailsSection': 'Details',
      'relatedTo': 'Related to',
      'received': 'Received',
      'read': 'Read',
      'unread': 'Unread',
      'type': 'Type',
      'deleteBtn': 'Delete',

      // Settings (additional)
      'settingsTitle': 'Settings',
      'submitFeedback': 'Submit feedback or report a problem',
      'inappropriateContent': 'Inappropriate Content',
      'spamHarassment': 'Spam or Harassment',
      'bugTechnical': 'Bug or Technical Issue',
      'suspiciousUser': 'Suspicious User',
      'other': 'Other',
      'failedDeleteAccount': 'Failed to delete account: {error}',
      'failedSubmit': 'Failed to submit: {error}',
      'privacyPolicyBody': 'Your privacy is important to us. We collect and use your personal information solely for the purpose of connecting blood donors with recipients. Your data is stored securely and is never shared with third parties without your explicit consent.',
      'termsBody': 'By using Blood Donor Network, you agree to use the platform responsibly. Donors must provide accurate health information. All interactions between donors and recipients are voluntary. The platform is not responsible for any medical outcomes resulting from donations.',
      'aboutDesc': 'Blood Donor Network is a platform that connects blood donors with patients and hospitals in need of blood donations.',
      'appLegalese': 'Connecting blood donors with those in need.',
      'versionLabel': 'Version 1.0.0',

      // Profile
      'profileTitle': 'Profile',
      'editProfileDesc': 'Update your personal information',
      'donationHistoryDesc': 'View your donation records',
      'notificationsProfileDesc': 'View your notifications',
      'savedHospitals': 'Saved Hospitals',
      'savedHospitalsDesc': 'View your saved hospitals',
      'healthTipsDesc': 'Blood donation guidelines and health advice',
      'settingsDesc': 'App preferences and account',
      'adminPanel': 'Admin Panel',
      'adminPanelDesc': 'Manage the platform',
      'versionString': 'Blood Donor Network v1.0.0',

      // Health Tips
      'donationEligibility': 'Donation Eligibility',
      'beforeYouDonate': 'Before You Donate',
      'duringDonation': 'During Donation',
      'afterYouDonate': 'After You Donate',
      'healthBenefits': 'Health Benefits of Donating Blood',
      'medicalNote': 'Medical Note',
      'medicalNoteBody': 'These guidelines are for general informational purposes. Always consult with healthcare professionals at your donation center for personalized advice.',
      'ageRequirement': 'Age: 18\u201365 years old',
      'weightRequirement': 'Weight: At least 50 kg (110 lbs)',
      'healthRequirement': 'General health: Feeling well on the day of donation',
      'hemoglobinRequirement': 'Hemoglobin levels: Must pass a simple blood test',
      'lastDonationRequirement': 'Last donation: At least 90 days ago (3 months)',
      'tipEatHealthy': 'Eat a healthy meal \u2014 avoid fatty foods',
      'tipDrinkWater': 'Drink plenty of water (500 ml extra)',
      'tipSleepWell': 'Get at least 6\u20138 hours of sleep',
      'tipNoAlcohol': 'Avoid alcohol for 24 hours before donation',
      'tipNoSmoking': 'Avoid smoking for at least 2 hours before',
      'tipRelax': 'Relax and stay calm \u2014 the process is safe',
      'tipDrawTime': 'The actual blood draw takes only 8\u201310 minutes',
      'tipTellStaff': 'Let staff know if you feel dizzy or uncomfortable',
      'tipListenMusic': 'Listen to music or chat to pass the time',
      'tipSnack': 'Have a snack and drink fluids (provided at the center)',
      'tipRest': 'Rest for 10\u201315 minutes before leaving',
      'tipNoExercise': 'Avoid heavy lifting or strenuous exercise for 24 hours',
      'tipNoAlcoholAfter': 'Avoid alcohol for the rest of the day',
      'tipDizzy': 'If you feel dizzy, sit down with your head between your knees',
      'benefitHeart': 'Reduces iron levels, lowering heart disease risk',
      'benefitCheckup': 'Provides a free mini health checkup (blood pressure, pulse, hemoglobin)',
      'benefitNewCells': 'Stimulates production of new blood cells',
      'benefitCalories': 'Burns about 650 calories per donation',
      'benefitSatisfaction': 'The satisfaction of saving up to 3 lives with one donation!',

      // Maps
      'mapView': 'Map View',
      'legend': 'Legend',
      'legendDonor': 'Donor',
      'legendHospital': 'Hospital',
      'legendBloodBank': 'Blood Bank',
      'legendEmergency': 'Emergency',
      'locationError': 'Could not get precise location',
      'pickLocation': 'Pick Location',
      'myLocation': 'My Location',
      'tapToPlaceMarker': 'Tap anywhere on the map to place a marker',
      'latitude': 'Latitude',
      'longitude': 'Longitude',
      'confirmLocation': 'Confirm Location',
      'selectedLocation': 'Selected Location',

      // Admin
      'adminDashboard': 'Admin Dashboard',
      'adminPanelTitle': 'Admin Panel',
      'manageNetwork': 'Manage the Blood Donor Network',
      'totalUsers': 'Total Users',
      'activeDonors': 'Active Donors',
      'totalRequests': 'Requests',
      'totalHospitals': 'Hospitals',
      'manageUsers': 'Manage Users',
      'manageUsersDesc': 'View and manage all platform users',
      'manageRequests': 'Manage Requests',
      'manageRequestsDesc': 'View and moderate blood requests',
      'announcements': 'Announcements',
      'announcementsDesc': 'Create and manage platform announcements',
      'approvals': 'Approvals',
      'approvalsDesc': 'Approve or reject hospitals and blood banks',
      'reports': 'Reports',
      'reportsDesc': 'Moderate user-submitted reports',
      'manageUsersTitle': 'Manage Users',
      'noUsersYet': 'No Users Yet',
      'usersWillAppear': 'Registered users will appear here.',
      'suspendUser': 'Suspend User',
      'suspendUserConfirm': 'Are you sure you want to suspend {name}?',
      'suspend': 'Suspend',
      'manageRequestsTitle': 'Manage Requests',
      'noRequestsAdmin': 'No Requests',
      'requestsWillAppear': 'Blood requests will appear here for moderation.',
      'remove': 'Remove',
      'removeRequest': 'Remove Request',
      'removeRequestConfirm': 'Are you sure you want to remove this request?',
      'announcementsTitle': 'Announcements',
      'noAnnouncements': 'No Announcements',
      'announcementsWillAppear': 'Create announcements to notify all platform users.',
      'createAnnouncement': 'Create Announcement',
      'title': 'Title',
      'enterTitle': 'Enter announcement title',
      'body': 'Body',
      'enterBody': 'Enter announcement body',
      'publishAnnouncement': 'Publish Announcement',
      'announcementPublished': 'Announcement published successfully',
      'failedToPublish': 'Failed to publish: {error}',
      'enterTitleBody': 'Please enter both title and body',
      'refresh': 'Refresh',
      'pendingApprovals': 'Pending Approvals',
      'hospitalsTab': 'Hospitals',
      'bloodBanksTab': 'Blood Banks',
      'allCaughtUp': 'All Caught Up',
      'noPendingHospitals': 'No pending hospitals to approve.',
      'noPendingBloodBanks': 'No pending blood banks to approve.',
      'reject': 'Reject',
      'approve': 'Approve',
      'rejectHospital': 'Reject Hospital',
      'rejectHospitalConfirm': 'Are you sure you want to reject "{name}"? This will permanently remove it.',
      'hospitalApproved': 'Hospital approved!',
      'hospitalRejectedRemoved': 'Hospital rejected and removed.',
      'rejectBloodBank': 'Reject Blood Bank',
      'rejectBloodBankConfirm': 'Are you sure you want to reject "{name}"? This will permanently remove it.',
      'bloodBankApproved': 'Blood bank approved!',
      'bloodBankRejectedRemoved': 'Blood bank rejected and removed.',
      'userReports': 'User Reports',
      'noReports': 'No Reports',
      'reportsWillAppear': 'User-submitted reports will appear here for moderation.',
      'failedToLoadReports': 'Failed to load reports: {error}',
      'dismiss': 'Dismiss',
      'dismissReport': 'Dismiss Report',
      'dismissReportConfirm': 'Mark this report as resolved?',
      'reportedUser': 'Reported User',
      'reason': 'Reason: {reason}',
      'reportedBy': 'Reported by: {name}',
      'date': 'Date: {date}',
      'noReasonProvided': 'No reason provided',
      'unknownUser': 'Unknown',

      // Hospital Dashboard
      'hospitalDashboard': 'Hospital Dashboard',
      'hospitalPanel': 'Hospital Panel',
      'manageHospital': 'Manage your hospital',
      'hospitalRegistered': 'Registered',
      'manage': 'Manage',
      'registerHospital': 'Register Hospital',
      'registerHospitalDesc': 'Add your hospital to the directory',
      'registerBloodBankShortDesc': 'Add a blood bank to your facility',
      'viewRequests': 'Blood Requests',
      'viewRequestsDesc': 'View incoming requests for your hospital',
      'viewDonationHistory': 'Donation History',
      'viewDonationHistoryDesc': 'View donation records at your hospital',
      'findDonorsAction': 'Find Donors',
      'findDonorsActionDesc': 'Search for nearby blood donors',
      'registrationInfo': 'Registration Info',
      'registrationInfoDesc': 'After registering, hospitals and blood banks will appear in the directory once verified by an admin.',
      'registerHospitalTitle': 'Register Hospital',
      'registerHospitalFull': 'Register Your Hospital',
      'registerHospitalDesc2': 'Add your hospital to the Blood Donor Network so patients can find and request blood from your facility.',
      'hospitalName': 'Hospital Name *',
      'operatingHours': 'Operating Hours',
      'enterHours': 'e.g. Mon-Fri 9AM-6PM, Sat 10AM-2PM',
      'hospitalRegisteredSuccess': 'Hospital registered successfully! It will appear after admin verification.',
      'failedToRegister': 'Failed to register hospital. Please try again.',
      'managedBy': 'Managed by: {name} ({email})',
      'permissionDenied': "You don't have permission to register. Please make sure you are logged in with a hospital manager account, or contact an admin.",

      // Create Request
      'createBloodRequest': 'Create Blood Request',
      'emergencyRequest': 'Emergency Blood Request',
      'fillDetails': 'Fill in the details to request blood donation',
      'locationDetected': 'Location detected',
      'detectingLocation': 'Detecting location...',
      'bloodGroupRequired': 'Blood Group Required',
      'selectBloodGroup': 'Select Blood Group',
      'unitsCount': 'Units Required',
      'numberOfUnits': 'Number of units needed',
      'priorityLevel': 'Priority Level',
      'normal': 'Normal',
      'urgent': 'Urgent',
      'critical': 'Critical',
      'additionalNotes': 'Additional Notes',
      'notesHint': 'Any specific requirements or information',
      'submitRequest': 'Submit Request',
      'requestSubmitted': 'Emergency request submitted successfully',
      'failedToSubmit': 'Failed to submit: {error}',
      'mustBeSignedIn': 'You must be signed in',

      // Common
      'searchHint': 'Search...',
      'back': 'Back',
      'confirmAction': 'Are you sure?',
      'yes': 'Yes',
      'no': 'No',
      'somethingWrong': 'Something went wrong',
    },
    'hi': {
      // General
      'appName': 'ब्लड डोनर नेटवर्क',
      'appTagline': 'जीवन बचाएं, रक्तदान करें',
      'ok': 'ठीक है',
      'cancel': 'रद्द करें',
      'close': 'बंद करें',
      'retry': 'पुनः प्रयास करें',
      'save': 'सहेजें',
      'delete': 'हटाएं',
      'confirm': 'पुष्टि करें',
      'loading': 'लोड हो रहा है...',
      'errorGeneric': 'त्रुटि: {error}',
      'failedToLoad': 'लोड करने में विफल: {error}',
      'pleaseSignIn': 'कृपया साइन इन करें',
      'retryBtn': 'पुनः प्रयास करें',
      'viewAll': 'सभी देखें',

      // Navigation
      'dashboard': 'डैशबोर्ड',
      'requests': 'अनुरोध',
      'donors': 'दाता',
      'hospitals': 'अस्पताल',
      'bloodBanks': 'रक्त बैंक',
      'profile': 'प्रोफ़ाइल',
      'settings': 'सेटिंग्स',
      'healthTips': 'स्वास्थ्य सुझाव',

      // Auth
      'welcomeBack': 'वापसी पर स्वागत है',
      'signIn': 'साइन इन करें',
      'signUp': 'साइन अप करें',
      'signOut': 'साइन आउट करें',
      'email': 'ईमेल',
      'password': 'पासवर्ड',
      'forgotPassword': 'पासवर्ड भूल गए?',
      'dontHaveAccount': 'खाता नहीं है? ',
      'alreadyHaveAccount': 'पहले से खाता है? ',
      'continueWithGoogle': 'Google से जारी रखें',
      'continueWithApple': 'Apple से जारी रखें',
      'register': 'पंजीकरण करें',
      'createAccount': 'खाता बनाएं',
      'joinNetwork': 'नेटवर्क से जुड़ें',
      'joinNetworkDesc': 'जीवन बचाने के लिए अपना खाता बनाएं',
      'iamA': 'मैं हूं...',
      'fullName': 'पूरा नाम',
      'enterFullName': 'अपना पूरा नाम दर्ज करें',
      'phoneNumber': 'फ़ोन नंबर',
      'enterPhoneNumber': 'अपना फ़ोन नंबर दर्ज करें',
      'confirmPassword': 'पासवर्ड की पुष्टि करें',
      'reenterPassword': 'अपना पासवर्ड पुनः दर्ज करें',
      'enterEmail': 'अपना ईमेल दर्ज करें',
      'enterPassword': 'अपना पासवर्ड दर्ज करें',
      'passwordsDoNotMatch': 'पासवर्ड मेल नहीं खाते',
      'accountCreated': 'खाता सफलतापूर्वक बनाया गया!',
      'donor': 'दाता',
      'patient': 'रोगी',
      'donateBloodDesc': 'रक्तदान करें और जीवन बचाएं',
      'requestBloodDesc': 'आपात स्थिति में रक्त का अनुरोध करें',
      'orContinueWith': 'या इससे जारी रखें',
      'resetPassword': 'पासवर्ड रीसेट करें',
      'forgotPasswordTitle': 'पासवर्ड भूल गए?',
      'enterEmailDesc': 'अपना ईमेल पता दर्ज करें और हम आपको पासवर्ड रीसेट करने के निर्देश भेजेंगे।',
      'enterRegisteredEmail': 'अपना पंजीकृत ईमेल दर्ज करें',
      'sendResetLink': 'रीसेट लिंक भेजें',
      'backToSignIn': 'साइन इन पर वापस जाएं',
      'emailSent': 'ईमेल भेज दिया गया!',
      'emailSentDesc': 'पासवर्ड रीसेट लिंक के लिए अपना ईमेल जांचें। इसे आने में कुछ मिनट लग सकते हैं।',
      'verifyEmail': 'अपना ईमेल सत्यापित करें',
      'pleaseVerifyEmail': 'पूर्ण पहुंच सक्षम करने के लिए कृपया अपना ईमेल सत्यापित करें',
      'verify': 'सत्यापित करें',
      'failedToSendCode': 'कोड भेजने में विफल: {error}',
      'enter6DigitCode': 'इस पर भेजा गया 6 अंकों का कोड दर्ज करें',
      'verifyEmailBtn': 'ईमेल सत्यापित करें',
      'didNotReceiveCode': 'कोड नहीं मिला? ',
      'resend': 'पुनः भेजें',
      'resendIn': '{seconds} सेकंड में पुनः भेजें',
      'useDifferentEmail': 'अलग ईमेल का उपयोग करें',
      'youCanAlsoClick': 'आप अपने ईमेल पर भेजे गए सत्यापन लिंक पर भी क्लिक कर सकते हैं। ऐप इसे स्वचालित रूप से पहचान लेगा।',

      // Onboarding
      'skip': 'छोड़ें',
      'next': 'अगला',
      'getStarted': 'शुरू करें',
      'findDonors': 'रक्तदाता खोजें',
      'findDonorsDesc': 'आपात स्थिति में तुरंत अपने क्षेत्र में पात्र रक्तदाताओं से जुड़ें।',
      'realTimeLocation': 'रीयल-टाइम लोकेशन',
      'realTimeLocationDesc': 'GPS आधारित खोज आपको निकटतम उपलब्ध दाताओं को मानचित्र पर दिखाती है।',
      'instantNotifications': 'तत्काल सूचनाएं',
      'instantNotificationsDesc': 'आपातकालीन रक्त अनुरोध प्राप्त करें और जीवन बचाने के लिए तुरंत प्रतिक्रिया दें।',

      // Dashboard
      'hello': 'नमस्ते',
      'readyToSaveLives': 'आज जीवन बचाने के लिए तैयार हैं?',
      'welcomeToApp': 'ब्लड डोनर नेटवर्क में आपका स्वागत है',
      'updateProfileMsg': 'पात्रता जांचने के लिए अपनी प्रोफ़ाइल अपडेट करें',
      'bloodGroup': 'रक्त समूह',
      'donations': 'दान',
      'unitsDonated': 'दान की गई इकाइयां',
      'age': 'आयु',
      'quickActions': 'त्वरित कार्रवाई',
      'findDonorsBtn': 'दाता खोजें',
      'history': 'इतिहास',
      'activeRequests': 'सक्रिय अनुरोध',
      'noActiveRequests': 'कोई सक्रिय अनुरोध नहीं',
      'emergencyRequestsHere': 'आपातकालीन अनुरोध यहां दिखाई देंगे',
      'donationSummary': 'दान सारांश',
      'units': 'इकाइयां',
      'donorAvailability': 'दाता उपलब्धता',
      'availableToDonate': 'आप दान करने के लिए उपलब्ध हैं',
      'toggleToReceive': 'अनुरोध प्राप्त करने के लिए टॉगल करें',
      'notificationsSection': 'सूचनाएं',
      'eligibleToDonate': 'दान करने योग्य',
      'eligibleNow': 'अब दान करने के लिए पात्र',
      'notEligible': 'पात्र नहीं',

      // Donor Profile
      'donorProfile': 'दाता प्रोफ़ाइल',
      'bloodDonor': 'रक्त दाता',
      'member': 'सदस्य',
      'edit': 'संपादित करें',
      'bloodInformation': 'रक्त जानकारी',
      'contact': 'संपर्क',
      'weight': 'वजन',
      'gender': 'लिंग',
      'weightKg': '{weight} किग्रा',
      'nA': 'एन/ए',
      'available': 'उपलब्ध',
      'unavailable': 'अनुपलब्ध',
      'updateAvailability': 'उपलब्धता स्थिति अपडेट करें',
      'failedToUpdate': 'अपडेट करने में विफल: {error}',
      'editProfile': 'प्रोफ़ाइल संपादित करें',
      'personalInfo': 'व्यक्तिगत जानकारी',
      'medicalInfo': 'चिकित्सा जानकारी',
      'cityAddress': 'शहर / पता',
      'enterCity': 'अपना शहर दर्ज करें',
      'getCurrentLocation': 'वर्तमान स्थान प्राप्त करें',
      'locationSaved': 'स्थान निर्देशांक सहेजे गए',
      'saveChanges': 'परिवर्तन सहेजें',
      'profileUpdated': 'प्रोफ़ाइल सफलतापूर्वक अपडेट की गई',
      'locationUpdated': 'स्थान सफलतापूर्वक अपडेट किया गया!',
      'failedToGetLocation': 'स्थान प्राप्त करने में विफल: {error}',
      'loadingProfile': 'प्रोफ़ाइल लोड हो रही है...',

      // Patient
      'patientDashboard': 'रोगी डैशबोर्ड',
      'total': 'कुल',
      'active': 'सक्रिय',
      'fulfilled': 'पूर्ण',
      'myRequests': 'मेरे अनुरोध',
      'createRequest': 'अनुरोध बनाएं',
      'newRequest': 'नया अनुरोध',
      'noRequestsYet': 'अभी तक कोई अनुरोध नहीं',
      'noRequestsDesc': 'अपने पास दाता खोजने के लिए आपातकालीन रक्त अनुरोध बनाएं।',
      'bloodGroupBlood': '{bloodGroup} रक्त',
      'acceptedBy': '{name} द्वारा स्वीकृत',
      'cancelBtn': 'रद्द करें',
      'failedToLoadRequests': 'अनुरोध लोड करने में विफल: {error}',

      // Blood Requests
      'bloodRequests': 'रक्त अनुरोध',
      'noBloodRequests': 'कोई रक्त अनुरोध नहीं',
      'noRequestsDonor': 'आपातकालीन रक्त अनुरोध यहां दिखाई देंगे।',
      'noRequestsPatient': 'दाता खोजने के लिए आपातकालीन अनुरोध बनाएं।',
      'bloodGroupNeeded': '{bloodGroup} रक्त आवश्यक',
      'unitsRequired': '{units} इकाई(यां) आवश्यक',
      'acceptRequest': 'अनुरोध स्वीकार करें',
      'requestDetails': 'अनुरोध विवरण',
      'patientLabel': 'रोगी',
      'bloodGroupLabel': 'रक्त समूह',
      'unitsLabel': 'इकाइयां',
      'priorityLabel': 'प्राथमिकता',
      'statusLabel': 'स्थिति',
      'acceptedByLabel': 'द्वारा स्वीकृत',
      'notesLabel': 'नोट्स',
      'markAsCompleted': 'पूर्ण के रूप में चिह्नित करें',
      'cancelRequest': 'अनुरोध रद्द करें',
      'acceptAsDonor': 'दाता के रूप में अनुरोध स्वीकार करें',
      'requestNotFound': 'अनुरोध नहीं मिला',
      'failedToLoadRequest': 'अनुरोध लोड करने में विफल',
      'loadingRequest': 'अनुरोध लोड हो रहा है...',
      'completeDonation': 'दान पूरा करें',
      'donationDate': 'दान की तारीख',
      'selectDonationDate': 'दान की तारीख चुनें',
      'selectHospital': 'अस्पताल चुनें',
      'confirmDonation': 'दान की पुष्टि करें',
      'optionalRemarks': 'वैकल्पिक टिप्पणी (जैसे, स्थिति नोट्स)',
      'remarksLabel': 'टिप्पणी',

      // Nearby Donors
      'findDonorsTitle': 'दाता खोजें',
      'refreshLocation': 'स्थान ताज़ा करें',
      'all': 'सभी',
      'withinKm': '{distance} किमी के भीतर',
      'sortBy': 'क्रमबद्ध करें:',
      'nearest': 'निकटतम',
      'mostActive': 'सबसे सक्रिय',
      'highDonations': 'उच्च दान',
      'gettingLocation': 'आपका स्थान प्राप्त हो रहा है...',
      'searchingForDonors': 'दाताओं की खोज हो रही है...',
      'searchFailed': 'खोज विफल',
      'searchFailedDesc': 'दाता नहीं मिल सके। कृपया अपना कनेक्शन जांचें और पुनः प्रयास करें।',
      'donorsFound': '{count} दाता मिले',
      'donorSelected': '{name} चयनित',
      'couldNotCall': 'फ़ोन कॉल नहीं कर सका',
      'noDonorsBloodGroup': '{distance} किमी के भीतर कोई {bloodGroup} दाता उपलब्ध नहीं',
      'noDonorsDistance': '{distance} किमी के भीतर कोई उपलब्ध दाता नहीं',
      'tryAdjusting': 'दूरी बढ़ाएं या रक्त समूह फ़िल्टर बदलें।',

      // Hospitals
      'hospitalsTitle': 'अस्पताल',
      'searchHospitals': 'अस्पताल खोजें...',
      'noHospitalsFound': 'कोई अस्पताल नहीं मिला',
      'noHospitalsMatch': 'आपकी खोज से कोई अस्पताल मेल नहीं खाता। कोई अलग शब्द आज़माएं।',
      'noHospitalsDir': 'पंजीकृत अस्पताल उपलब्ध होने पर अस्पताल निर्देशिका यहां दिखाई देगी।',
      'verified': 'सत्यापित',
      'call': 'कॉल करें',
      'navigate': 'नेविगेट करें',
      'couldNotOpenMaps': 'मानचित्र नहीं खोल सका',
      'failedToLoadHospitals': 'अस्पताल लोड करने में विफल',
      'hospitalsWillAppear': 'पंजीकृत होने पर अस्पताल यहां दिखाई देंगे।',

      // Blood Banks
      'bloodBanksTitle': 'रक्त बैंक',
      'searchBloodBanks': 'रक्त बैंक खोजें...',
      'noBloodBanksFound': 'कोई रक्त बैंक नहीं मिला',
      'noBloodBanksMatch': 'आपकी खोज से कोई रक्त बैंक मेल नहीं खाता। कोई अलग शब्द आज़माएं।',
      'bloodBanksWillAppear': 'पंजीकृत होने पर रक्त बैंक यहां दिखाई देंगे।',
      'failedToLoadBloodBanks': 'रक्त बैंक लोड करने में विफल',
      'registerBloodBank': 'रक्त बैंक पंजीकृत करें',
      'bloodBankRegistered': 'रक्त बैंक सफलतापूर्वक पंजीकृत!',
      'registerBloodBankTitle': 'रक्त बैंक पंजीकृत करें',
      'registerBloodBankDesc': 'एक रक्त बैंक को नेटवर्क में जोड़ें ताकि दाता और अस्पताल आपका स्थान पा सकें।',
      'bloodBankName': 'रक्त बैंक का नाम *',
      'address': 'पता',
      'locationRequired': 'स्थान *',
      'tapToSelectLocation': 'मानचित्र खोलने और स्थान चुनने के लिए टैप करें',
      'pleaseSelectLocation': 'कृपया मानचित्र पर एक स्थान चुनें',

      // Donation History
      'donationHistory': 'दान इतिहास',
      'donorLevel': 'दाता स्तर',
      'totalDons': 'कुल दान',
      'lastDonation': 'पिछला दान',
      'nextEligible': 'अगली पात्रता',
      'none': 'कोई नहीं',
      'historySection': 'इतिहास',
      'atHospital': '{name} पर',
      'aHospital': 'एक अस्पताल',
      'achievements': 'उपलब्धियां',
      'firstBlood': 'पहला रक्त',
      'superDonor': 'सुपर डोनर',
      'hero': 'हीरो',
      'make1Donation': '1 दान करें',
      'reach5Donations': '5 दान तक पहुंचें',
      'reach10Donations': '10 दान तक पहुंचें',
      'noDonationsYet': 'अभी तक कोई दान नहीं',
      'donationsWillAppear': 'आपका दान इतिहास पहले दान के बाद यहां दिखाई देगा।',
      'failedToLoadStats': 'आंकड़े लोड करने में विफल: {error}',
      'newLevel': 'नया',
      'bronze': 'कांस्य',
      'silver': 'रजत',
      'gold': 'स्वर्ण',

      // Notifications
      'notificationsTitle': 'सूचनाएं',
      'markAllRead': 'सभी पढ़ी गईं ({count})',
      'noNotifications': 'कोई सूचना नहीं',
      'noNotificationsDesc': 'आपको आपातकालीन अनुरोधों, अपडेट और घोषणाओं के बारे में सूचनाएं यहां प्राप्त होंगी।',
      'failedToLoadNotifications': 'सूचनाएं लोड करने में विफल',
      'view': 'देखें',
      'notificationDetail': 'सूचना',
      'deleteNotification': 'सूचना हटाएं',
      'deleteNotificationConfirm': 'क्या आप वाकई इस सूचना को हटाना चाहते हैं?',
      'share': 'साझा करें',
      'notificationCopied': 'सूचना क्लिपबोर्ड पर कॉपी की गई',
      'emergencyAlert': 'आपातकालीन अलर्ट',
      'reminder': 'अनुस्मारक',
      'announcement': 'घोषणा',
      'general': 'सामान्य',
      'detailsSection': 'विवरण',
      'relatedTo': 'संबंधित',
      'received': 'प्राप्त',
      'read': 'पढ़ा',
      'unread': 'अपठित',
      'type': 'प्रकार',
      'deleteBtn': 'हटाएं',

      // Settings (additional)
      'settingsTitle': 'सेटिंग्स',
      'submitFeedback': 'प्रतिक्रिया सबमिट करें या समस्या रिपोर्ट करें',
      'inappropriateContent': 'अनुचित सामग्री',
      'spamHarassment': 'स्पैम या उत्पीड़न',
      'bugTechnical': 'बग या तकनीकी समस्या',
      'suspiciousUser': 'संदिग्ध उपयोगकर्ता',
      'other': 'अन्य',
      'failedDeleteAccount': 'खाता हटाने में विफल: {error}',
      'failedSubmit': 'सबमिट करने में विफल: {error}',
      'privacyPolicyBody': 'आपकी गोपनीयता हमारे लिए महत्वपूर्ण है। हम आपकी व्यक्तिगत जानकारी केवल रक्तदाताओं और प्राप्तकर्ताओं को जोड़ने के उद्देश्य से एकत्र और उपयोग करते हैं। आपका डेटा सुरक्षित रूप से संग्रहीत किया जाता है और आपकी स्पष्ट सहमति के बिना तीसरे पक्ष के साथ कभी साझा नहीं किया जाता है।',
      'termsBody': 'ब्लड डोनर नेटवर्क का उपयोग करके, आप प्लेटफ़ॉर्म का जिम्मेदारी से उपयोग करने के लिए सहमत होते हैं। दाताओं को सटीक स्वास्थ्य जानकारी प्रदान करनी होगी। दाताओं और प्राप्तकर्ताओं के बीच सभी बातचीत स्वैच्छिक है। प्लेटफ़ॉर्म दान से होने वाले किसी भी चिकित्सा परिणाम के लिए जिम्मेदार नहीं है।',
      'aboutDesc': 'ब्लड डोनर नेटवर्क एक ऐसा प्लेटफ़ॉर्म है जो रक्तदाताओं को रक्तदान की आवश्यकता वाले रोगियों और अस्पतालों से जोड़ता है।',
      'appLegalese': 'जरूरतमंदों को रक्तदाताओं से जोड़ना।',
      'versionLabel': 'संस्करण 1.0.0',

      // Profile
      'profileTitle': 'प्रोफ़ाइल',
      'editProfileDesc': 'अपनी व्यक्तिगत जानकारी अपडेट करें',
      'donationHistoryDesc': 'अपने दान रिकॉर्ड देखें',
      'notificationsProfileDesc': 'अपनी सूचनाएं देखें',
      'savedHospitals': 'सहेजे गए अस्पताल',
      'savedHospitalsDesc': 'अपने सहेजे गए अस्पताल देखें',
      'healthTipsDesc': 'रक्तदान दिशानिर्देश और स्वास्थ्य सलाह',
      'settingsDesc': 'ऐप प्राथमिकताएं और खाता',
      'adminPanel': 'एडमिन पैनल',
      'adminPanelDesc': 'प्लेटफ़ॉर्म प्रबंधित करें',
      'versionString': 'ब्लड डोनर नेटवर्क v1.0.0',

      // Health Tips
      'donationEligibility': 'दान करने की पात्रता',
      'beforeYouDonate': 'दान करने से पहले',
      'duringDonation': 'दान के दौरान',
      'afterYouDonate': 'दान करने के बाद',
      'healthBenefits': 'रक्तदान के स्वास्थ्य लाभ',
      'medicalNote': 'चिकित्सा नोट',
      'medicalNoteBody': 'ये दिशानिर्देश सामान्य जानकारी के उद्देश्य से हैं। व्यक्तिगत सलाह के लिए हमेशा अपने दान केंद्र के स्वास्थ्य पेशेवरों से परामर्श करें।',
      'ageRequirement': 'आयु: 18\u201365 वर्ष',
      'weightRequirement': 'वजन: कम से कम 50 किग्रा',
      'healthRequirement': 'सामान्य स्वास्थ्य: दान के दिन अच्छा महसूस करना',
      'hemoglobinRequirement': 'हीमोग्लोबिन स्तर: एक साधारण रक्त परीक्षण पास करना होगा',
      'lastDonationRequirement': 'पिछला दान: कम से कम 90 दिन पहले (3 महीने)',
      'tipEatHealthy': 'स्वस्थ भोजन खाएं \u2014 वसायुक्त भोजन से बचें',
      'tipDrinkWater': 'खूब पानी पिएं (500 मिली अतिरिक्त)',
      'tipSleepWell': 'कम से कम 6\u20138 घंटे की नींद लें',
      'tipNoAlcohol': 'दान से 24 घंटे पहले शराब से बचें',
      'tipNoSmoking': 'दान से कम से कम 2 घंटे पहले धूम्रपान से बचें',
      'tipRelax': 'आराम करें और शांत रहें \u2014 प्रक्रिया सुरक्षित है',
      'tipDrawTime': 'वास्तविक रक्त निकासी में केवल 8\u201310 मिनट लगते हैं',
      'tipTellStaff': 'यदि आपको चक्कर या असुविधा महसूस हो तो स्टाफ को बताएं',
      'tipListenMusic': 'समय बिताने के लिए संगीत सुनें या बातचीत करें',
      'tipSnack': 'नाश्ता करें और तरल पदार्थ पिएं (केंद्र पर उपलब्ध)',
      'tipRest': 'जाने से पहले 10\u201315 मिनट आराम करें',
      'tipNoExercise': '24 घंटे तक भारी वजन उठाने या जोरदार व्यायाम से बचें',
      'tipNoAlcoholAfter': 'बाकी दिन शराब से बचें',
      'tipDizzy': 'यदि चक्कर आए, तो अपने घुटनों के बीच सिर रखकर बैठें',
      'benefitHeart': 'आयरन के स्तर को कम करता है, हृदय रोग के जोखिम को कम करता है',
      'benefitCheckup': 'मुफ्त मिनी स्वास्थ्य जांच प्रदान करता है (रक्तचाप, नाड़ी, हीमोग्लोबिन)',
      'benefitNewCells': 'नई रक्त कोशिकाओं के उत्पादन को उत्तेजित करता है',
      'benefitCalories': 'प्रति दान लगभग 650 कैलोरी जलाता है',
      'benefitSatisfaction': 'एक दान से 3 जीवन बचाने का संतोष!',

      // Maps
      'mapView': 'मानचित्र दृश्य',
      'legend': 'किंवदंती',
      'legendDonor': 'दाता',
      'legendHospital': 'अस्पताल',
      'legendBloodBank': 'रक्त बैंक',
      'legendEmergency': 'आपातकाल',
      'locationError': 'सटीक स्थान प्राप्त नहीं कर सका',
      'pickLocation': 'स्थान चुनें',
      'myLocation': 'मेरा स्थान',
      'tapToPlaceMarker': 'मार्कर लगाने के लिए मानचित्र पर कहीं भी टैप करें',
      'latitude': 'अक्षांश',
      'longitude': 'देशांतर',
      'confirmLocation': 'स्थान की पुष्टि करें',
      'selectedLocation': 'चयनित स्थान',

      // Admin
      'adminDashboard': 'एडमिन डैशबोर्ड',
      'adminPanelTitle': 'एडमिन पैनल',
      'manageNetwork': 'ब्लड डोनर नेटवर्क प्रबंधित करें',
      'totalUsers': 'कुल उपयोगकर्ता',
      'activeDonors': 'सक्रिय दाता',
      'totalRequests': 'अनुरोध',
      'totalHospitals': 'अस्पताल',
      'manageUsers': 'उपयोगकर्ता प्रबंधित करें',
      'manageUsersDesc': 'सभी प्लेटफ़ॉर्म उपयोगकर्ताओं को देखें और प्रबंधित करें',
      'manageRequests': 'अनुरोध प्रबंधित करें',
      'manageRequestsDesc': 'रक्त अनुरोध देखें और मॉडरेट करें',
      'announcements': 'घोषणाएं',
      'announcementsDesc': 'प्लेटफ़ॉर्म घोषणाएं बनाएं और प्रबंधित करें',
      'approvals': 'अनुमोदन',
      'approvalsDesc': 'अस्पतालों और रक्त बैंकों को अनुमोदित या अस्वीकार करें',
      'reports': 'रिपोर्ट',
      'reportsDesc': 'उपयोगकर्ता द्वारा सबमिट की गई रिपोर्ट मॉडरेट करें',
      'manageUsersTitle': 'उपयोगकर्ता प्रबंधित करें',
      'noUsersYet': 'अभी तक कोई उपयोगकर्ता नहीं',
      'usersWillAppear': 'पंजीकृत उपयोगकर्ता यहां दिखाई देंगे।',
      'suspendUser': 'उपयोगकर्ता निलंबित करें',
      'suspendUserConfirm': 'क्या आप वाकई {name} को निलंबित करना चाहते हैं?',
      'suspend': 'निलंबित करें',
      'manageRequestsTitle': 'अनुरोध प्रबंधित करें',
      'noRequestsAdmin': 'कोई अनुरोध नहीं',
      'requestsWillAppear': 'रक्त अनुरोध मॉडरेशन के लिए यहां दिखाई देंगे।',
      'remove': 'हटाएं',
      'removeRequest': 'अनुरोध हटाएं',
      'removeRequestConfirm': 'क्या आप वाकई इस अनुरोध को हटाना चाहते हैं?',
      'announcementsTitle': 'घोषणाएं',
      'noAnnouncements': 'कोई घोषणा नहीं',
      'announcementsWillAppear': 'सभी प्लेटफ़ॉर्म उपयोगकर्ताओं को सूचित करने के लिए घोषणाएं बनाएं।',
      'createAnnouncement': 'घोषणा बनाएं',
      'title': 'शीर्षक',
      'enterTitle': 'घोषणा का शीर्षक दर्ज करें',
      'body': 'विवरण',
      'enterBody': 'घोषणा का विवरण दर्ज करें',
      'publishAnnouncement': 'घोषणा प्रकाशित करें',
      'announcementPublished': 'घोषणा सफलतापूर्वक प्रकाशित!',
      'failedToPublish': 'प्रकाशित करने में विफल: {error}',
      'enterTitleBody': 'कृपया शीर्षक और विवरण दोनों दर्ज करें',
      'refresh': 'ताज़ा करें',
      'pendingApprovals': 'लंबित अनुमोदन',
      'hospitalsTab': 'अस्पताल',
      'bloodBanksTab': 'रक्त बैंक',
      'allCaughtUp': 'सब ठीक है',
      'noPendingHospitals': 'अनुमोदन के लिए कोई लंबित अस्पताल नहीं।',
      'noPendingBloodBanks': 'अनुमोदन के लिए कोई लंबित रक्त बैंक नहीं।',
      'reject': 'अस्वीकार करें',
      'approve': 'अनुमोदित करें',
      'rejectHospital': 'अस्पताल अस्वीकार करें',
      'rejectHospitalConfirm': 'क्या आप वाकई "{name}" को अस्वीकार करना चाहते हैं? इसे स्थायी रूप से हटा दिया जाएगा।',
      'hospitalApproved': 'अस्पताल अनुमोदित!',
      'hospitalRejectedRemoved': 'अस्पताल अस्वीकार और हटा दिया गया।',
      'rejectBloodBank': 'रक्त बैंक अस्वीकार करें',
      'rejectBloodBankConfirm': 'क्या आप वाकई "{name}" को अस्वीकार करना चाहते हैं? इसे स्थायी रूप से हटा दिया जाएगा।',
      'bloodBankApproved': 'रक्त बैंक अनुमोदित!',
      'bloodBankRejectedRemoved': 'रक्त बैंक अस्वीकार और हटा दिया गया।',
      'userReports': 'उपयोगकर्ता रिपोर्ट',
      'noReports': 'कोई रिपोर्ट नहीं',
      'reportsWillAppear': 'उपयोगकर्ता द्वारा सबमिट की गई रिपोर्ट मॉडरेशन के लिए यहां दिखाई देंगी।',
      'failedToLoadReports': 'रिपोर्ट लोड करने में विफल: {error}',
      'dismiss': 'खारिज करें',
      'dismissReport': 'रिपोर्ट खारिज करें',
      'dismissReportConfirm': 'इस रिपोर्ट को हल के रूप में चिह्नित करें?',
      'reportedUser': 'रिपोर्ट किया गया उपयोगकर्ता',
      'reason': 'कारण: {reason}',
      'reportedBy': 'द्वारा रिपोर्ट: {name}',
      'date': 'दिनांक: {date}',
      'noReasonProvided': 'कोई कारण नहीं दिया गया',
      'unknownUser': 'अज्ञात',

      // Hospital Dashboard
      'hospitalDashboard': 'अस्पताल डैशबोर्ड',
      'hospitalPanel': 'अस्पताल पैनल',
      'manageHospital': 'अपने अस्पताल का प्रबंधन करें',
      'hospitalRegistered': 'पंजीकृत',
      'manage': 'प्रबंधित करें',
      'registerHospital': 'अस्पताल पंजीकृत करें',
      'registerHospitalDesc': 'अपने अस्पताल को निर्देशिका में जोड़ें',
      'registerBloodBankShortDesc': 'अपनी सुविधा में रक्त बैंक जोड़ें',
      'viewRequests': 'रक्त अनुरोध',
      'viewRequestsDesc': 'अपने अस्पताल के लिए आने वाले अनुरोध देखें',
      'viewDonationHistory': 'दान इतिहास',
      'viewDonationHistoryDesc': 'अपने अस्पताल में दान रिकॉर्ड देखें',
      'findDonorsAction': 'दाता खोजें',
      'findDonorsActionDesc': 'पास के रक्तदाताओं की खोज करें',
      'registrationInfo': 'पंजीकरण जानकारी',
      'registrationInfoDesc': 'पंजीकरण के बाद, अस्पताल और रक्त बैंक एडमिन द्वारा सत्यापित होने के बाद निर्देशिका में दिखाई देंगे।',
      'registerHospitalTitle': 'अस्पताल पंजीकृत करें',
      'registerHospitalFull': 'अपना अस्पताल पंजीकृत करें',
      'registerHospitalDesc2': 'अपने अस्पताल को ब्लड डोनर नेटवर्क में जोड़ें ताकि मरीज आपकी सुविधा से रक्त का अनुरोध कर सकें।',
      'hospitalName': 'अस्पताल का नाम *',
      'operatingHours': 'संचालन के घंटे',
      'enterHours': 'जैसे: सोम-शुक्र सुबह9-शाम6, शनि सुबह10-दोपहर2',
      'hospitalRegisteredSuccess': 'अस्पताल सफलतापूर्वक पंजीकृत! यह एडमिन सत्यापन के बाद दिखाई देगा।',
      'failedToRegister': 'अस्पताल पंजीकृत करने में विफल। कृपया पुनः प्रयास करें।',
      'managedBy': '{name} ({email}) द्वारा प्रबंधित',
      'permissionDenied': 'आपके पास पंजीकरण करने की अनुमति नहीं है। कृपया सुनिश्चित करें कि आप अस्पताल प्रबंधक खाते से लॉग इन हैं, या एडमिन से संपर्क करें।',

      // Create Request
      'createBloodRequest': 'रक्त अनुरोध बनाएं',
      'emergencyRequest': 'आपातकालीन रक्त अनुरोध',
      'fillDetails': 'रक्तदान का अनुरोध करने के लिए विवरण भरें',
      'locationDetected': 'स्थान का पता चला',
      'detectingLocation': 'स्थान का पता लग रहा है...',
      'bloodGroupRequired': 'आवश्यक रक्त समूह',
      'selectBloodGroup': 'रक्त समूह चुनें',
      'unitsCount': 'आवश्यक इकाइयां',
      'numberOfUnits': 'आवश्यक इकाइयों की संख्या',
      'priorityLevel': 'प्राथमिकता स्तर',
      'normal': 'सामान्य',
      'urgent': 'तत्काल',
      'critical': 'गंभीर',
      'additionalNotes': 'अतिरिक्त नोट्स',
      'notesHint': 'कोई विशिष्ट आवश्यकता या जानकारी',
      'submitRequest': 'अनुरोध सबमिट करें',
      'requestSubmitted': 'आपातकालीन अनुरोध सफलतापूर्वक सबमिट किया गया',
      'failedToSubmit': 'सबमिट करने में विफल: {error}',
      'mustBeSignedIn': 'आपको साइन इन होना चाहिए',

      // Common
      'searchHint': 'खोजें...',
      'back': 'वापस',
      'confirmAction': 'क्या आप सुनिश्चित हैं?',
      'yes': 'हां',
      'no': 'नहीं',
      'somethingWrong': 'कुछ गलत हो गया',
    },
    'ur': {
      // General
      'appName': 'بلڈ ڈونر نیٹ ورک',
      'appTagline': 'جانیں بچائیں، خون عطیہ کریں',
      'ok': 'ٹھیک ہے',
      'cancel': 'منسوخ کریں',
      'close': 'بند کریں',
      'retry': 'دوبارہ کوشش کریں',
      'save': 'محفوظ کریں',
      'delete': 'حذف کریں',
      'confirm': 'تصدیق کریں',
      'loading': 'لوڈ ہو رہا ہے...',
      'errorGeneric': 'خرابی: {error}',
      'failedToLoad': 'لوڈ کرنے میں ناکام: {error}',
      'pleaseSignIn': 'براہ کرم سائن ان کریں',
      'retryBtn': 'دوبارہ کوشش کریں',
      'viewAll': 'سب دیکھیں',

      // Navigation
      'dashboard': 'ڈیش بورڈ',
      'requests': 'درخواستیں',
      'donors': 'عطیہ دہندگان',
      'hospitals': 'ہسپتال',
      'bloodBanks': 'بلڈ بینک',
      'profile': 'پروفائل',
      'settings': 'سیٹنگز',
      'healthTips': 'صحت کے مشورے',

      // Auth
      'welcomeBack': 'واپسی پر خوش آمدید',
      'signIn': 'سائن ان کریں',
      'signUp': 'سائن اپ کریں',
      'signOut': 'سائن آؤٹ کریں',
      'email': 'ای میل',
      'password': 'پاس ورڈ',
      'forgotPassword': 'پاس ورڈ بھول گئے؟',
      'dontHaveAccount': 'اکاؤنٹ نہیں ہے؟ ',
      'alreadyHaveAccount': 'پہلے سے اکاؤنٹ ہے؟ ',
      'continueWithGoogle': 'Google کے ساتھ جاری رکھیں',
      'continueWithApple': 'Apple کے ساتھ جاری رکھیں',
      'register': 'رجسٹر کریں',
      'createAccount': 'اکاؤنٹ بنائیں',
      'joinNetwork': 'نیٹ ورک سے جڑیں',
      'joinNetworkDesc': 'جانیں بچانے کے لیے اپنا اکاؤنٹ بنائیں',
      'iamA': 'میں ہوں...',
      'fullName': 'پورا نام',
      'enterFullName': 'اپنا پورا نام درج کریں',
      'phoneNumber': 'فون نمبر',
      'enterPhoneNumber': 'اپنا فون نمبر درج کریں',
      'confirmPassword': 'پاس ورڈ کی تصدیق کریں',
      'reenterPassword': 'اپنا پاس ورڈ دوبارہ درج کریں',
      'enterEmail': 'اپنا ای میل درج کریں',
      'enterPassword': 'اپنا پاس ورڈ درج کریں',
      'passwordsDoNotMatch': 'پاس ورڈ مماثل نہیں ہیں',
      'accountCreated': 'اکاؤنٹ کامیابی سے بن گیا!',
      'donor': 'عطیہ دہندہ',
      'patient': 'مریض',
      'donateBloodDesc': 'خون عطیہ کریں اور جانیں بچائیں',
      'requestBloodDesc': 'ہنگامی صورتحال میں خون کی درخواست کریں',
      'orContinueWith': 'یا اس کے ساتھ جاری رکھیں',
      'resetPassword': 'پاس ورڈ ری سیٹ کریں',
      'forgotPasswordTitle': 'پاس ورڈ بھول گئے؟',
      'enterEmailDesc': 'اپنا ای میل پتہ درج کریں اور ہم آپ کو پاس ورڈ ری سیٹ کرنے کی ہدایات بھیجیں گے۔',
      'enterRegisteredEmail': 'اپنا رجسٹرڈ ای میل درج کریں',
      'sendResetLink': 'ری سیٹ لنک بھیجیں',
      'backToSignIn': 'سائن ان پر واپس جائیں',
      'emailSent': 'ای میل بھیج دیا گیا!',
      'emailSentDesc': 'پاس ورڈ ری سیٹ لنک کے لیے اپنا ای میل چیک کریں۔ اسے آنے میں چند منٹ لگ سکتے ہیں۔',
      'verifyEmail': 'اپنے ای میل کی تصدیق کریں',
      'pleaseVerifyEmail': 'مکمل رسائی کے لیے براہ کرم اپنا ای میل تصدیق کریں',
      'verify': 'تصدیق کریں',
      'failedToSendCode': 'کوڈ بھیجنے میں ناکام: {error}',
      'enter6DigitCode': 'اس پر بھیجا گیا 6 ہندسوں کا کوڈ درج کریں',
      'verifyEmailBtn': 'ای میل کی تصدیق کریں',
      'didNotReceiveCode': 'کوڈ نہیں ملا؟ ',
      'resend': 'دوبارہ بھیجیں',
      'resendIn': '{seconds} سیکنڈ میں دوبارہ بھیجیں',
      'useDifferentEmail': 'مختلف ای میل استعمال کریں',
      'youCanAlsoClick': 'آپ اپنے ای میل پر بھیجے گئے تصدیقی لنک پر بھی کلک کر سکتے ہیں۔ ایپ خود بخود اسے پہچان لے گی۔',

      // Onboarding
      'skip': 'چھوڑیں',
      'next': 'اگلا',
      'getStarted': 'شروع کریں',
      'findDonors': 'خون کے عطیہ دہندگان تلاش کریں',
      'findDonorsDesc': 'ہنگامی صورتحال میں فوری طور پر اپنے علاقے میں اہل عطیہ دہندگان سے رابطہ کریں۔',
      'realTimeLocation': 'حقیقی وقت کی لوکیشن',
      'realTimeLocationDesc': 'GPS پر مبنی تلاش آپ کو نقشے پر قریب ترین دستیاب عطیہ دہندگان دکھاتی ہے۔',
      'instantNotifications': 'فوری اطلاعات',
      'instantNotificationsDesc': 'خون کی ہنگامی درخواستیں وصول کریں اور جلد زندگیاں بچانے کے لیے جواب دیں۔',

      // Dashboard
      'hello': 'ہیلو',
      'readyToSaveLives': 'آج جانیں بچانے کے لیے تیار ہیں؟',
      'welcomeToApp': 'بلڈ ڈونر نیٹ ورک میں خوش آمدید',
      'updateProfileMsg': 'اہلیت جانچنے کے لیے اپنی پروفائل اپ ڈیٹ کریں',
      'bloodGroup': 'بلڈ گروپ',
      'donations': 'عطیات',
      'unitsDonated': 'عطیہ کردہ یونٹس',
      'age': 'عمر',
      'quickActions': 'فوری کارروائیاں',
      'findDonorsBtn': 'عطیہ دہندگان تلاش کریں',
      'history': 'تاریخ',
      'activeRequests': 'فعال درخواستیں',
      'noActiveRequests': 'کوئی فعال درخواست نہیں',
      'emergencyRequestsHere': 'ہنگامی درخواستیں یہاں ظاہر ہوں گی',
      'donationSummary': 'عطیہ کا خلاصہ',
      'units': 'یونٹس',
      'donorAvailability': 'عطیہ دہندہ کی دستیابی',
      'availableToDonate': 'آپ عطیہ کرنے کے لیے دستیاب ہیں',
      'toggleToReceive': 'درخواستیں وصول کرنے کے لیے ٹوگل کریں',
      'notificationsSection': 'اطلاعات',
      'eligibleToDonate': 'عطیہ کرنے کے اہل',
      'eligibleNow': 'اب عطیہ کرنے کے اہل',
      'notEligible': 'اہل نہیں',

      // Donor Profile
      'donorProfile': 'عطیہ دہندہ کا پروفائل',
      'bloodDonor': 'خون کا عطیہ دہندہ',
      'member': 'رکن',
      'edit': 'ترمیم کریں',
      'bloodInformation': 'خون کی معلومات',
      'contact': 'رابطہ',
      'weight': 'وزن',
      'gender': 'جنس',
      'weightKg': '{weight} کلو',
      'nA': 'N/A',
      'available': 'دستیاب',
      'unavailable': 'غیر دستیاب',
      'updateAvailability': 'دستیابی کی حیثیت اپ ڈیٹ کریں',
      'failedToUpdate': 'اپ ڈیٹ کرنے میں ناکام: {error}',
      'editProfile': 'پروفائل میں ترمیم کریں',
      'personalInfo': 'ذاتی معلومات',
      'medicalInfo': 'طبی معلومات',
      'cityAddress': 'شہر / پتہ',
      'enterCity': 'اپنا شہر درج کریں',
      'getCurrentLocation': 'موجودہ لوکیشن حاصل کریں',
      'locationSaved': 'لوکیشن کوآرڈینیٹ محفوظ ہو گئے',
      'saveChanges': 'تبدیلیاں محفوظ کریں',
      'profileUpdated': 'پروفائل کامیابی سے اپ ڈیٹ ہو گئی',
      'locationUpdated': 'لوکیشن کامیابی سے اپ ڈیٹ ہو گئی!',
      'failedToGetLocation': 'لوکیشن حاصل کرنے میں ناکام: {error}',
      'loadingProfile': 'پروفائل لوڈ ہو رہی ہے...',

      // Patient
      'patientDashboard': 'مریض ڈیش بورڈ',
      'total': 'کل',
      'active': 'فعال',
      'fulfilled': 'مکمل',
      'myRequests': 'میری درخواستیں',
      'createRequest': 'درخواست بنائیں',
      'newRequest': 'نئی درخواست',
      'noRequestsYet': 'ابھی تک کوئی درخواست نہیں',
      'noRequestsDesc': 'اپنے قریب عطیہ دہندگان تلاش کرنے کے لیے ہنگامی خون کی درخواست بنائیں۔',
      'bloodGroupBlood': '{bloodGroup} خون',
      'acceptedBy': '{name} کے ذریعے قبول شدہ',
      'cancelBtn': 'منسوخ کریں',
      'failedToLoadRequests': 'درخواستیں لوڈ کرنے میں ناکام: {error}',

      // Blood Requests
      'bloodRequests': 'خون کی درخواستیں',
      'noBloodRequests': 'کوئی خون کی درخواست نہیں',
      'noRequestsDonor': 'خون کی ہنگامی درخواستیں یہاں ظاہر ہوں گی۔',
      'noRequestsPatient': 'عطیہ دہندگان تلاش کرنے کے لیے ہنگامی درخواست بنائیں۔',
      'bloodGroupNeeded': '{bloodGroup} خون درکار ہے',
      'unitsRequired': '{units} یونٹ(ٹس) درکار',
      'acceptRequest': 'درخواست قبول کریں',
      'requestDetails': 'درخواست کی تفصیلات',
      'patientLabel': 'مریض',
      'bloodGroupLabel': 'بلڈ گروپ',
      'unitsLabel': 'یونٹس',
      'priorityLabel': 'ترجیح',
      'statusLabel': 'حیثیت',
      'acceptedByLabel': 'قبول کردہ',
      'notesLabel': 'نوٹس',
      'markAsCompleted': 'مکمل کے طور پر نشان زد کریں',
      'cancelRequest': 'درخواست منسوخ کریں',
      'acceptAsDonor': 'عطیہ دہندہ کے طور پر درخواست قبول کریں',
      'requestNotFound': 'درخواست نہیں ملی',
      'failedToLoadRequest': 'درخواست لوڈ کرنے میں ناکام',
      'loadingRequest': 'درخواست لوڈ ہو رہی ہے...',
      'completeDonation': 'عطیہ مکمل کریں',
      'donationDate': 'عطیہ کی تاریخ',
      'selectDonationDate': 'عطیہ کی تاریخ منتخب کریں',
      'selectHospital': 'ہسپتال منتخب کریں',
      'confirmDonation': 'عطیہ کی تصدیق کریں',
      'optionalRemarks': 'اختیاری ریمارکس (مثلاً، حالت کے نوٹس)',
      'remarksLabel': 'ریمارکس',

      // Nearby Donors
      'findDonorsTitle': 'عطیہ دہندگان تلاش کریں',
      'refreshLocation': 'لوکیشن تازہ کریں',
      'all': 'سب',
      'withinKm': '{distance} کلومیٹر کے اندر',
      'sortBy': 'ترتیب دیں:',
      'nearest': 'قریب ترین',
      'mostActive': 'سب سے زیادہ فعال',
      'highDonations': 'زیادہ عطیات',
      'gettingLocation': 'آپ کی لوکیشن مل رہی ہے...',
      'searchingForDonors': 'عطیہ دہندگان کی تلاش ہو رہی ہے...',
      'searchFailed': 'تلاش ناکام',
      'searchFailedDesc': 'عطیہ دہندگان نہیں مل سکے۔ براہ کرم اپنا کنکشن چیک کریں اور دوبارہ کوشش کریں۔',
      'donorsFound': '{count} عطیہ دہندہ(دہندگان) ملے',
      'donorSelected': '{name} منتخب',
      'couldNotCall': 'فون کال نہیں کر سکا',
      'noDonorsBloodGroup': '{distance} کلومیٹر کے اندر کوئی {bloodGroup} عطیہ دہندہ دستیاب نہیں',
      'noDonorsDistance': '{distance} کلومیٹر کے اندر کوئی دستیاب عطیہ دہندہ نہیں',
      'tryAdjusting': 'فاصلہ بڑھائیں یا بلڈ گروپ فلٹر تبدیل کریں۔',

      // Hospitals
      'hospitalsTitle': 'ہسپتال',
      'searchHospitals': 'ہسپتال تلاش کریں...',
      'noHospitalsFound': 'کوئی ہسپتال نہیں ملا',
      'noHospitalsMatch': 'آپ کی تلاش سے کوئی ہسپتال مماثل نہیں۔ کوئی مختلف اصطلاح آزمائیں۔',
      'noHospitalsDir': 'رجسٹرڈ ہسپتال دستیاب ہونے پر ہسپتالوں کی ڈائریکٹری یہاں ظاہر ہوگی۔',
      'verified': 'تصدیق شدہ',
      'call': 'کال کریں',
      'navigate': 'نیویگیٹ کریں',
      'couldNotOpenMaps': 'نقشہ نہیں کھول سکا',
      'failedToLoadHospitals': 'ہسپتال لوڈ کرنے میں ناکام',
      'hospitalsWillAppear': 'رجسٹر ہونے پر ہسپتال یہاں ظاہر ہوں گے۔',

      // Blood Banks
      'bloodBanksTitle': 'بلڈ بینک',
      'searchBloodBanks': 'بلڈ بینک تلاش کریں...',
      'noBloodBanksFound': 'کوئی بلڈ بینک نہیں ملا',
      'noBloodBanksMatch': 'آپ کی تلاش سے کوئی بلڈ بینک مماثل نہیں۔ کوئی مختلف اصطلاح آزمائیں۔',
      'bloodBanksWillAppear': 'رجسٹر ہونے پر بلڈ بینک یہاں ظاہر ہوں گے۔',
      'failedToLoadBloodBanks': 'بلڈ بینک لوڈ کرنے میں ناکام',
      'registerBloodBank': 'بلڈ بینک رجسٹر کریں',
      'bloodBankRegistered': 'بلڈ بینک کامیابی سے رجسٹر ہو گیا!',
      'registerBloodBankTitle': 'بلڈ بینک رجسٹر کریں',
      'registerBloodBankDesc': 'نیٹ ورک میں بلڈ بینک شامل کریں تاکہ عطیہ دہندگان اور ہسپتال آپ کا مقام تلاش کر سکیں۔',
      'bloodBankName': 'بلڈ بینک کا نام *',
      'address': 'پتہ',
      'locationRequired': 'مقام *',
      'tapToSelectLocation': 'نقشہ کھولنے اور مقام منتخب کرنے کے لیے تھپتھپائیں',
      'pleaseSelectLocation': 'براہ کرم نقشے پر ایک مقام منتخب کریں',

      // Donation History
      'donationHistory': 'عطیہ کی تاریخ',
      'donorLevel': 'عطیہ دہندہ کی سطح',
      'totalDons': 'کل عطیات',
      'lastDonation': 'آخری عطیہ',
      'nextEligible': 'اگلی اہلیت',
      'none': 'کوئی نہیں',
      'historySection': 'تاریخ',
      'atHospital': '{name} پر',
      'aHospital': 'ایک ہسپتال',
      'achievements': 'کامیابیاں',
      'firstBlood': 'پہلا خون',
      'superDonor': 'سپر ڈونر',
      'hero': 'ہیرو',
      'make1Donation': '1 عطیہ کریں',
      'reach5Donations': '5 عطیات تک پہنچیں',
      'reach10Donations': '10 عطیات تک پہنچیں',
      'noDonationsYet': 'ابھی تک کوئی عطیہ نہیں',
      'donationsWillAppear': 'آپ کے عطیہ کی تاریخ پہلے عطیہ کے بعد یہاں ظاہر ہوگی۔',
      'failedToLoadStats': 'اعداد و شمار لوڈ کرنے میں ناکام: {error}',
      'newLevel': 'نیا',
      'bronze': 'کانسی',
      'silver': 'چاندی',
      'gold': 'سونا',

      // Notifications
      'notificationsTitle': 'اطلاعات',
      'markAllRead': 'سب پڑھے گئے ({count})',
      'noNotifications': 'کوئی اطلاع نہیں',
      'noNotificationsDesc': 'آپ کو ہنگامی درخواستوں، اپ ڈیٹس اور اعلانات کے بارے میں اطلاعات یہاں ملیں گی۔',
      'failedToLoadNotifications': 'اطلاعات لوڈ کرنے میں ناکام',
      'view': 'دیکھیں',
      'notificationDetail': 'اطلاع',
      'deleteNotification': 'اطلاع حذف کریں',
      'deleteNotificationConfirm': 'کیا آپ واقعی اس اطلاع کو حذف کرنا چاہتے ہیں؟',
      'share': 'شیئر کریں',
      'notificationCopied': 'اطلاع کلپ بورڈ پر کاپی ہو گئی',
      'emergencyAlert': 'ہنگامی الرٹ',
      'reminder': 'یاد دہانی',
      'announcement': 'اعلان',
      'general': 'عام',
      'detailsSection': 'تفصیلات',
      'relatedTo': 'متعلقہ',
      'received': 'موصول ہوا',
      'read': 'پڑھا گیا',
      'unread': 'نہیں پڑھا گیا',
      'type': 'قسم',
      'deleteBtn': 'حذف کریں',

      // Settings (additional)
      'settingsTitle': 'سیٹنگز',
      'submitFeedback': 'فیڈ بیک جمع کروائیں یا مسئلہ رپورٹ کریں',
      'inappropriateContent': 'نامناسب مواد',
      'spamHarassment': 'سپیم یا ہراسانی',
      'bugTechnical': 'بگ یا تکنیکی مسئلہ',
      'suspiciousUser': 'مشتبہ صارف',
      'other': 'دیگر',
      'failedDeleteAccount': 'اکاؤنٹ حذف کرنے میں ناکام: {error}',
      'failedSubmit': 'جمع کرانے میں ناکام: {error}',
      'privacyPolicyBody': 'آپ کی پرائیویسی ہمارے لیے اہم ہے۔ ہم آپ کی ذاتی معلومات صرف خون کے عطیہ دہندگان اور وصول کنندگان کو جوڑنے کے مقصد کے لیے جمع اور استعمال کرتے ہیں۔ آپ کا ڈیٹا محفوظ طریقے سے ذخیرہ کیا جاتا ہے اور آپ کی واضح رضامندی کے بغیر تیسرے فریق کے ساتھ کبھی شیئر نہیں کیا جاتا۔',
      'termsBody': 'بلڈ ڈونر نیٹ ورک استعمال کرکے، آپ پلیٹ فارم کو ذمہ داری سے استعمال کرنے سے اتفاق کرتے ہیں۔ عطیہ دہندگان کو درست صحت کی معلومات فراہم کرنی ہوں گی۔ عطیہ دہندگان اور وصول کنندگان کے درمیان تمام تعاملات رضاکارانہ ہیں۔ پلیٹ فارم عطیات کے نتیجے میں ہونے والے کسی بھی طبی نتائج کا ذمہ دار نہیں ہے۔',
      'aboutDesc': 'بلڈ ڈونر نیٹ ورک ایک ایسا پلیٹ فارم ہے جو خون کے عطیہ دہندگان کو مریضوں اور ہسپتالوں سے جوڑتا ہے جنہیں خون کے عطیات کی ضرورت ہوتی ہے۔',
      'appLegalese': 'ضرورت مندوں کو خون کے عطیہ دہندگان سے جوڑنا۔',
      'versionLabel': 'ورژن 1.0.0',

      // Profile
      'profileTitle': 'پروفائل',
      'editProfileDesc': 'اپنی ذاتی معلومات اپ ڈیٹ کریں',
      'donationHistoryDesc': 'اپنے عطیہ کے ریکارڈ دیکھیں',
      'notificationsProfileDesc': 'اپنی اطلاعات دیکھیں',
      'savedHospitals': 'محفوظ کردہ ہسپتال',
      'savedHospitalsDesc': 'اپنے محفوظ کردہ ہسپتال دیکھیں',
      'healthTipsDesc': 'خون کے عطیہ کے رہنما اصول اور صحت کے مشورے',
      'settingsDesc': 'ایپ کی ترجیحات اور اکاؤنٹ',
      'adminPanel': 'ایڈمن پینل',
      'adminPanelDesc': 'پلیٹ فارم کا نظم کریں',
      'versionString': 'بلڈ ڈونر نیٹ ورک v1.0.0',

      // Health Tips
      'donationEligibility': 'عطیہ کرنے کی اہلیت',
      'beforeYouDonate': 'عطیہ کرنے سے پہلے',
      'duringDonation': 'عطیہ کے دوران',
      'afterYouDonate': 'عطیہ کرنے کے بعد',
      'healthBenefits': 'خون عطیہ کرنے کے صحت کے فوائد',
      'medicalNote': 'طبی نوٹ',
      'medicalNoteBody': 'یہ رہنما اصول عمومی معلومات کے مقاصد کے لیے ہیں۔ ذاتی مشورے کے لیے ہمیشہ اپنے عطیہ مرکز کے صحت کے پیشہ ور افراد سے مشورہ کریں۔',
      'ageRequirement': 'عمر: 18\u201365 سال',
      'weightRequirement': 'وزن: کم از کم 50 کلوگرام',
      'healthRequirement': 'عام صحت: عطیہ کے دن اچھا محسوس کرنا',
      'hemoglobinRequirement': 'ہیموگلوبن کی سطح: سادہ خون کا ٹیسٹ پاس کرنا ضروری',
      'lastDonationRequirement': 'آخری عطیہ: کم از کم 90 دن پہلے (3 ماہ)',
      'tipEatHealthy': 'صحت بخش کھانا کھائیں \u2014 چکنائی والے کھانے سے پرہیز کریں',
      'tipDrinkWater': 'خوب پانی پئیں (500 ملی لیٹر اضافی)',
      'tipSleepWell': 'کم از کم 6\u20138 گھنٹے کی نیند لیں',
      'tipNoAlcohol': 'عطیہ سے 24 گھنٹے پہلے شراب سے پرہیز کریں',
      'tipNoSmoking': 'عطیہ سے کم از کم 2 گھنٹے پہلے سگریٹ نوشی سے پرہیز کریں',
      'tipRelax': 'آرام کریں اور پرسکون رہیں \u2014 عمل محفوظ ہے',
      'tipDrawTime': 'خون نکالنے میں صرف 8\u201310 منٹ لگتے ہیں',
      'tipTellStaff': 'اگر آپ کو چکر یا بے آرامی محسوس ہو تو عملے کو بتائیں',
      'tipListenMusic': 'وقت گزارنے کے لیے موسیقی سنیں یا بات چیت کریں',
      'tipSnack': 'ناشتہ کریں اور سیال پیئیں (مرکز پر دستیاب)',
      'tipRest': 'جانے سے پہلے 10\u201315 منٹ آرام کریں',
      'tipNoExercise': '24 گھنٹے بھاری وزن اٹھانے یا سخت ورزش سے پرہیز کریں',
      'tipNoAlcoholAfter': 'باقی دن شراب سے پرہیز کریں',
      'tipDizzy': 'اگر چکر آئے تو اپنے گھٹنوں کے درمیان سر رکھ کر بیٹھ جائیں',
      'benefitHeart': 'آئرن کی سطح کم کرتا ہے، دل کی بیماری کا خطرہ کم کرتا ہے',
      'benefitCheckup': 'مفت منی ہیلتھ چیک اپ فراہم کرتا ہے (بلڈ پریشر، نبض، ہیموگلوبن)',
      'benefitNewCells': 'نئے خون کے خلیات کی پیداوار کو تحریک دیتا ہے',
      'benefitCalories': 'فی عطیہ تقریباً 650 کیلوریز جلاتا ہے',
      'benefitSatisfaction': 'ایک عطیہ سے 3 زندگیاں بچانے کا اطمینان!',

      // Maps
      'mapView': 'نقشہ کا منظر',
      'legend': 'علامات',
      'legendDonor': 'عطیہ دہندہ',
      'legendHospital': 'ہسپتال',
      'legendBloodBank': 'بلڈ بینک',
      'legendEmergency': 'ہنگامی',
      'locationError': 'درست مقام حاصل نہیں کر سکا',
      'pickLocation': 'مقام منتخب کریں',
      'myLocation': 'میرا مقام',
      'tapToPlaceMarker': 'مارکر رکھنے کے لیے نقشے پر کہیں بھی تھپتھپائیں',
      'latitude': 'عرض البلد',
      'longitude': 'طول البلد',
      'confirmLocation': 'مقام کی تصدیق کریں',
      'selectedLocation': 'منتخب کردہ مقام',

      // Admin
      'adminDashboard': 'ایڈمن ڈیش بورڈ',
      'adminPanelTitle': 'ایڈمن پینل',
      'manageNetwork': 'بلڈ ڈونر نیٹ ورک کا نظم کریں',
      'totalUsers': 'کل صارفین',
      'activeDonors': 'فعال عطیہ دہندگان',
      'totalRequests': 'درخواستیں',
      'totalHospitals': 'ہسپتال',
      'manageUsers': 'صارفین کا نظم کریں',
      'manageUsersDesc': 'تمام پلیٹ فارم صارفین دیکھیں اور ان کا نظم کریں',
      'manageRequests': 'درخواستوں کا نظم کریں',
      'manageRequestsDesc': 'خون کی درخواستیں دیکھیں اور ان کی نگرانی کریں',
      'announcements': 'اعلانات',
      'announcementsDesc': 'پلیٹ فارم کے اعلانات بنائیں اور ان کا نظم کریں',
      'approvals': 'منظوریاں',
      'approvalsDesc': 'ہسپتالوں اور بلڈ بینکوں کو منظور یا مسترد کریں',
      'reports': 'رپورٹس',
      'reportsDesc': 'صارفین کی جمع کردہ رپورٹس کی نگرانی کریں',
      'manageUsersTitle': 'صارفین کا نظم کریں',
      'noUsersYet': 'ابھی تک کوئی صارف نہیں',
      'usersWillAppear': 'رجسٹرڈ صارفین یہاں ظاہر ہوں گے۔',
      'suspendUser': 'صارف کو معطل کریں',
      'suspendUserConfirm': 'کیا آپ واقعی {name} کو معطل کرنا چاہتے ہیں؟',
      'suspend': 'معطل کریں',
      'manageRequestsTitle': 'درخواستوں کا نظم کریں',
      'noRequestsAdmin': 'کوئی درخواست نہیں',
      'requestsWillAppear': 'خون کی درخواستیں نگرانی کے لیے یہاں ظاہر ہوں گی۔',
      'remove': 'ہٹائیں',
      'removeRequest': 'درخواست ہٹائیں',
      'removeRequestConfirm': 'کیا آپ واقعی اس درخواست کو ہٹانا چاہتے ہیں؟',
      'announcementsTitle': 'اعلانات',
      'noAnnouncements': 'کوئی اعلان نہیں',
      'announcementsWillAppear': 'تمام پلیٹ فارم صارفین کو مطلع کرنے کے لیے اعلانات بنائیں۔',
      'createAnnouncement': 'اعلان بنائیں',
      'title': 'عنوان',
      'enterTitle': 'اعلان کا عنوان درج کریں',
      'body': 'تفصیل',
      'enterBody': 'اعلان کی تفصیل درج کریں',
      'publishAnnouncement': 'اعلان شائع کریں',
      'announcementPublished': 'اعلان کامیابی سے شائع ہو گیا!',
      'failedToPublish': 'شائع کرنے میں ناکام: {error}',
      'enterTitleBody': 'براہ کرم عنوان اور تفصیل دونوں درج کریں',
      'refresh': 'تازہ کریں',
      'pendingApprovals': 'زیر التواء منظوریاں',
      'hospitalsTab': 'ہسپتال',
      'bloodBanksTab': 'بلڈ بینک',
      'allCaughtUp': 'سب ٹھیک ہے',
      'noPendingHospitals': 'منظوری کے لیے کوئی زیر التواء ہسپتال نہیں۔',
      'noPendingBloodBanks': 'منظوری کے لیے کوئی زیر التواء بلڈ بینک نہیں۔',
      'reject': 'مسترد کریں',
      'approve': 'منظور کریں',
      'rejectHospital': 'ہسپتال مسترد کریں',
      'rejectHospitalConfirm': 'کیا آپ واقعی "{name}" کو مسترد کرنا چاہتے ہیں؟ اسے مستقل طور پر ہٹا دیا جائے گا۔',
      'hospitalApproved': 'ہسپتال منظور!',
      'hospitalRejectedRemoved': 'ہسپتال مسترد اور ہٹا دیا گیا۔',
      'rejectBloodBank': 'بلڈ بینک مسترد کریں',
      'rejectBloodBankConfirm': 'کیا آپ واقعی "{name}" کو مسترد کرنا چاہتے ہیں؟ اسے مستقل طور پر ہٹا دیا جائے گا۔',
      'bloodBankApproved': 'بلڈ بینک منظور!',
      'bloodBankRejectedRemoved': 'بلڈ بینک مسترد اور ہٹا دیا گیا۔',
      'userReports': 'صارف رپورٹس',
      'noReports': 'کوئی رپورٹ نہیں',
      'reportsWillAppear': 'صارفین کی جمع کردہ رپورٹس نگرانی کے لیے یہاں ظاہر ہوں گی۔',
      'failedToLoadReports': 'رپورٹس لوڈ کرنے میں ناکام: {error}',
      'dismiss': 'ختم کریں',
      'dismissReport': 'رپورٹ ختم کریں',
      'dismissReportConfirm': 'اس رپورٹ کو حل شدہ کے طور پر نشان زد کریں؟',
      'reportedUser': 'رپورٹ کردہ صارف',
      'reason': 'وجہ: {reason}',
      'reportedBy': 'رپورٹ کردہ: {name}',
      'date': 'تاریخ: {date}',
      'noReasonProvided': 'کوئی وجہ فراہم نہیں کی گئی',
      'unknownUser': 'نامعلوم',

      // Hospital Dashboard
      'hospitalDashboard': 'ہسپتال ڈیش بورڈ',
      'hospitalPanel': 'ہسپتال پینل',
      'manageHospital': 'اپنے ہسپتال کا نظم کریں',
      'hospitalRegistered': 'رجسٹرڈ',
      'manage': 'نظم کریں',
      'registerHospital': 'ہسپتال رجسٹر کریں',
      'registerHospitalDesc': 'اپنے ہسپتال کو ڈائریکٹری میں شامل کریں',
      'registerBloodBankShortDesc': 'اپنی سہولت میں بلڈ بینک شامل کریں',
      'viewRequests': 'خون کی درخواستیں',
      'viewRequestsDesc': 'اپنے ہسپتال کے لیے آنے والی درخواستیں دیکھیں',
      'viewDonationHistory': 'عطیہ کی تاریخ',
      'viewDonationHistoryDesc': 'اپنے ہسپتال میں عطیہ کے ریکارڈ دیکھیں',
      'findDonorsAction': 'عطیہ دہندگان تلاش کریں',
      'findDonorsActionDesc': 'قریب کے خون کے عطیہ دہندگان تلاش کریں',
      'registrationInfo': 'رجسٹریشن کی معلومات',
      'registrationInfoDesc': 'رجسٹریشن کے بعد، ہسپتال اور بلڈ بینک ایڈمن کے ذریعے تصدیق کے بعد ڈائریکٹری میں ظاہر ہوں گے۔',
      'registerHospitalTitle': 'ہسپتال رجسٹر کریں',
      'registerHospitalFull': 'اپنا ہسپتال رجسٹر کریں',
      'registerHospitalDesc2': 'اپنے ہسپتال کو بلڈ ڈونر نیٹ ورک میں شامل کریں تاکہ مریض آپ کی سہولت سے خون کی درخواست کر سکیں۔',
      'hospitalName': 'ہسپتال کا نام *',
      'operatingHours': 'آپریٹنگ اوقات',
      'enterHours': 'مثلاً: پیر-جمعہ صبح9-شام6، ہفتہ صبح10-دوپہر2',
      'hospitalRegisteredSuccess': 'ہسپتال کامیابی سے رجسٹر ہو گیا! یہ ایڈمن کی تصدیق کے بعد ظاہر ہوگا۔',
      'failedToRegister': 'ہسپتال رجسٹر کرنے میں ناکام۔ براہ کرم دوبارہ کوشش کریں۔',
      'managedBy': '{name} ({email}) کے ذریعے زیر نظم',
      'permissionDenied': 'آپ کے پاس رجسٹر کرنے کی اجازت نہیں ہے۔ براہ کرم یقینی بنائیں کہ آپ ہسپتال مینیجر اکاؤنٹ سے لاگ ان ہیں، یا ایڈمن سے رابطہ کریں۔',

      // Create Request
      'createBloodRequest': 'خون کی درخواست بنائیں',
      'emergencyRequest': 'خون کی ہنگامی درخواست',
      'fillDetails': 'خون کے عطیہ کی درخواست کرنے کے لیے تفصیلات بھریں',
      'locationDetected': 'مقام کا پتہ چل گیا',
      'detectingLocation': 'مقام کا پتہ لگ رہا ہے...',
      'bloodGroupRequired': 'مطلوبہ بلڈ گروپ',
      'selectBloodGroup': 'بلڈ گروپ منتخب کریں',
      'unitsCount': 'مطلوبہ یونٹس',
      'numberOfUnits': 'مطلوبہ یونٹس کی تعداد',
      'priorityLevel': 'ترجیحی سطح',
      'normal': 'عام',
      'urgent': 'فوری',
      'critical': 'سنگین',
      'additionalNotes': 'اضافی نوٹس',
      'notesHint': 'کوئی خاص ضروریات یا معلومات',
      'submitRequest': 'درخواست جمع کروائیں',
      'requestSubmitted': 'ہنگامی درخواست کامیابی سے جمع کر دی گئی',
      'failedToSubmit': 'جمع کرانے میں ناکام: {error}',
      'mustBeSignedIn': 'آپ کو سائن ان ہونا چاہیے',

      // Common
      'searchHint': 'تلاش کریں...',
      'back': 'واپس',
      'confirmAction': 'کیا آپ کو یقین ہے؟',
      'yes': 'ہاں',
      'no': 'نہیں',
      'somethingWrong': 'کچھ غلط ہو گیا',
    },
  };

  /// Translate [key] into [locale]. Falls back to English if the key or
  /// locale is missing.
  static String tr(String key, [String locale = 'en']) {
    return _translations[locale]?[key] ?? _translations['en']?[key] ?? key;
  }

  /// All supported locales.
  static const List<String> supportedLocales = ['en', 'hi', 'ur'];

  /// Human-readable names for each supported locale.
  static const Map<String, String> localeNames = {
    'en': 'English',
    'hi': 'हिन्दी',
    'ur': 'اردو',
  };

  /// Map locale code to Flutter [Locale].
  static Locale toFlutterLocale(String code) {
    return switch (code) {
      'hi' => const Locale('hi'),
      'ur' => const Locale('ur'),
      _ => const Locale('en'),
    };
  }
}
