// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCN0Nia9mNnnwt9QzwKAtgCn_PbTIYvArQ',
    appId: '1:349854014984:web:facdfdee4e4d9df80f3bbd',
    messagingSenderId: '349854014984',
    projectId: 'blooddonation-a1131',
    authDomain: 'blooddonation-a1131.firebaseapp.com',
    storageBucket: 'blooddonation-a1131.firebasestorage.app',
    measurementId: 'G-QB00EZL39N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPA35uazmF33Sv0Wt45X-3rYjs5bJkspU',
    appId: '1:349854014984:android:6497cbd34dc569710f3bbd',
    messagingSenderId: '349854014984',
    projectId: 'blooddonation-a1131',
    storageBucket: 'blooddonation-a1131.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDssKUMRUbxKpFmzNgGkCXKWF9d7D7ABhk',
    appId: '1:349854014984:ios:f4ea32ea444cc7d50f3bbd',
    messagingSenderId: '349854014984',
    projectId: 'blooddonation-a1131',
    storageBucket: 'blooddonation-a1131.firebasestorage.app',
    iosBundleId: 'com.example.bloodDonation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDssKUMRUbxKpFmzNgGkCXKWF9d7D7ABhk',
    appId: '1:349854014984:ios:f4ea32ea444cc7d50f3bbd',
    messagingSenderId: '349854014984',
    projectId: 'blooddonation-a1131',
    storageBucket: 'blooddonation-a1131.firebasestorage.app',
    iosBundleId: 'com.example.bloodDonation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCN0Nia9mNnnwt9QzwKAtgCn_PbTIYvArQ',
    appId: '1:349854014984:web:5d977f5d171dc4f10f3bbd',
    messagingSenderId: '349854014984',
    projectId: 'blooddonation-a1131',
    authDomain: 'blooddonation-a1131.firebaseapp.com',
    storageBucket: 'blooddonation-a1131.firebasestorage.app',
    measurementId: 'G-FVY244V0W9',
  );
}
